// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/active/[id].tsx";
import * as $2 from "./routes/active/index.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/contact.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/news.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Form.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Particles.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/active/[id].tsx": $1,
    "./routes/active/index.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/contact.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/news.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Form.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Particles.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
